Fix kafka micro install
PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam pull request #29
Opened 2022-10-08 21:38 UTC by donhk

fixed some build issues with flink install script

2022-10-08 21:44 UTC, donhk commented
after the changes the script works as expected

```
[donhk@workpc Building-Big-Data-Pipelines-with-Apache-Beam]$ kubectl get pods -l app=flink
NAME                                 READY   STATUS    RESTARTS       AGE
flink-jobmanager-5f7d864b54-lh6dz    1/1     Running   0              69m
flink-taskmanager-5b6d4bf4f9-bxq6x   2/2     Running   14 (28m ago)   69m
```

2022-10-09 00:25 UTC, donhk commented
![image](https://user-images.githubusercontent.com/11450292/194732100-33000d50-937e-4d8d-b7ee-50d96d9196f0.png)

2022-10-15 00:04 UTC, donhk commented
![image](https://user-images.githubusercontent.com/11450292/195959463-b3d314e2-24df-4bcc-ae4d-71938cea808c.png)

latest changes fix the remaining issues

2023-02-21 13:43 UTC, je-ik commented
@donhk can you please rebase this on current `main`?

2023-03-24 21:32 UTC, donhk commented
@je-ik just updated the branch from main

2023-03-27 08:00 UTC, je-ik requested changes
Thanks for the PR! A have two minor comments, it would be better to keep the number of layers low, which is why I'd like to keep the RUN commands squashed. We can merge this after. Thanks again!

2023-03-27 08:00 UTC, je-ik commented on env/docker/harness/Dockerfile
> +RUN apt -y update
Can you please squash these commands to single one? i.e.
```
 RUN apt -y update && python4 -m pip uninstall -y six && ...
```

2023-03-27 08:00 UTC, je-ik commented on env/manifests/kafka_micro.yaml
> +apiVersion: policy/v1
I had some issues with `v1` in the version of minikube that was mentioned in the book. I'd rather keep it, if possible.

2025-05-17 03:44 UTC, closed without merging